# Generated by Django 3.0.7 on 2021-02-05 12:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_altitude', models.IntegerField(verbose_name='Target Altitude')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
        ),
        migrations.CreateModel(
            name='LocalVelocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
            options={
                'verbose_name': 'Local Velocity',
                'verbose_name_plural': 'Local Velocities',
                'db_table': 'local_velocity',
            },
        ),
        migrations.CreateModel(
            name='LocalPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
            options={
                'verbose_name': 'Local Position',
                'verbose_name_plural': 'Local Positions',
                'db_table': 'local_position',
            },
        ),
        migrations.CreateModel(
            name='GlobalPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
            options={
                'verbose_name': 'Global Position',
                'verbose_name_plural': 'Global Positions',
                'db_table': 'global_position',
            },
        ),
        migrations.CreateModel(
            name='GlobalHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
            options={
                'verbose_name': 'Global Home',
                'verbose_name_plural': 'Global Home',
                'db_table': 'global_home',
            },
        ),
    ]
