# Generated by Django 3.0.7 on 2021-02-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'get_latest_by': 'id', 'verbose_name': 'Movement', 'verbose_name_plural': 'Movements'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelTable(
            name='movement',
            table='movement',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
    ]
