# Generated by Django 3.0.7 on 2021-02-07 07:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
