# Generated by Django 3.0.7 on 2021-02-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210209_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Is Finished'),
        ),
    ]
