# Generated by Django 3.0.7 on 2021-02-20 06:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210217_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('local_position', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('local_velocity', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('global_position', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('global_home', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
            options={
                'verbose_name': 'Drone Data',
                'verbose_name_plural': 'Drone Datas',
                'db_table': 'drone_data',
                'get_latest_by': 'id',
            },
        ),
        migrations.RemoveField(
            model_name='globalposition',
            name='session',
        ),
        migrations.RemoveField(
            model_name='localposition',
            name='session',
        ),
        migrations.RemoveField(
            model_name='localvelocity',
            name='session',
        ),
        migrations.DeleteModel(
            name='GlobalHome',
        ),
        migrations.DeleteModel(
            name='GlobalPosition',
        ),
        migrations.DeleteModel(
            name='LocalPosition',
        ),
        migrations.DeleteModel(
            name='LocalVelocity',
        ),
    ]
