# Generated by Django 3.0.7 on 2021-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210220_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='safety_distance',
            field=models.IntegerField(default=5, verbose_name='Safety Distance'),
        ),
    ]
